# -*- coding: utf-8 -*-
"""De opening van elke kaart: twee controleerbare feiten die botsen.

Elke opening sluit aan op bevinding 01 van de persoonlijke pagina, zodat de
prospect na het scannen ziet dat de kaart en de pagina over hetzelfde gaan.
"""

OPENING = {
"10DAYS": "Op jullie servicepagina staat dat een mail binnen 48 uur wordt beantwoord. Diezelfde balie bedient veertien taal- en marktvarianten, met 358 artikelen erachter.",
"ANNA plus NINA": "Op de contactpagina vond ik webshop@anna-nina.nl en verder geen lijn om te bellen. In de webshop erachter staan 819 artikelen.",
"Aaiko": "Jullie webshop draait in 27 taal- en marktvarianten. Op de contactpagina staat een mailadres en verder geen telefoonnummer.",
"Beaumont Amsterdam": "Jullie reviewers zijn lovend over de kwaliteit en de verpakking. In diezelfde reviews gaat de kritiek bijna altijd over de klantenservice.",
"Bedrukken nl": "Op jullie site staat de klantenservice als bereikbaar van 09.30 tot 17.00. Op elke pagina staat daarnaast een chat en een WhatsApp-knop, en die kennen dat tijdslot niet.",
"Blackstone Shoes": "Jullie vernieuwden het IT-landschap om de organisatie sneller te maken. Op de klantenservicepagina loopt het contact nog altijd via de mail.",
"Blond Amsterdam": "Jullie klantenservice is bereikbaar tussen 09:00 en 17:00. De WhatsApp-knop op de site staat er de andere zestien uur ook.",
"Buddha to Buddha": "Op jullie servicepagina staat dat je binnen vijf werkdagen antwoord krijgt. Op dezelfde pagina staat een WhatsApp-knop, en daar rekent iemand op dezelfde dag.",
"Butcher of Blue": "Jullie collectie groeide van heren naar dames en ligt inmiddels bij verkooppunten door heel Noord-Europa. Een eigen reviewpagina waar die kopers iets kwijt kunnen, vond ik nergens.",
"CLUSE": "Op jullie contactpagina staat press@cluse.com als adres. Daarachter draait een webshop in zeven taalvarianten met 361 artikelen.",
"CanvasCompany": "Op jullie site staat dat je binnen 48 uur antwoord krijgt. Op diezelfde site staat een chatvenster dat de bezoeker iets heel anders belooft.",
"Carnibest": "Op jullie site staat dat de klantenservice bereikbaar is van maandag tot en met donderdag, tot half vijf. Een bestelling die op vrijdag aankomt, wacht dus tot maandag op antwoord.",
"Casimoda": "Op jullie site staat dat een vraag binnen 48 uur wordt beantwoord. Het assortiment waar die vragen over gaan, telt meer dan tienduizend hoesjes.",
"Catwalk Junkie": "Jullie beloven antwoord binnen 24 uur en de balie is open van negen tot zes. De webshop erachter draait in veertig taal- en marktvarianten.",
"Circle of Trust": "Op jullie servicepagina staat antwoord binnen een werkdag. Op Trustpilot staan inmiddels 1.679 mensen die daar iets over te zeggen hadden.",
"Colourful Rebel": "Jullie klantenservice draait van maandag tot en met donderdag. De webshop draait in 33 taalvarianten en sinds januari ook via Zalando.",
"Confirm Clothing": "Jullie klantenservice is bereikbaar tussen negen en vijf. Bestellen kan de hele nacht, en de mail die daaruit komt wacht tot de volgende ochtend.",
"Difrax": "Jullie klantenservice is bereikbaar van maandag tot donderdag. De site voert 75 taal- en marktvarianten.",
"Dogs Companion": "Jullie klantenservice is open van tien uur tot vier uur. In de reviews lees ik vragen over levertijd en over de vulling terug, precies het soort vraag dat iemand liever meteen stelt.",
"Eyelove Brillen": "Jullie hebben winkels in acht plaatsen in Nederland en Belgie en ruim drieduizend reviews. De klantenservice zit achter een balie, van half negen tot zes.",
"Fitchef": "Elke week staat er bij jullie een nieuw weekmenu online. Een vraag daarover kan alleen per mail, want een telefoonnummer staat er niet bij.",
"Flinndal": "Jullie hebben ruim 22.000 reviews en een abonnementsmodel met vaste leveringen. Elke wijziging in zo'n abonnement komt bij dezelfde balie binnen.",
"Floer": "Jullie klantenservice is bereikbaar tot half zes. De verkoop loopt daarnaast via een dealernetwerk in Nederland en Belgie, dus vragen over een vloer komen langs twee wegen binnen.",
"Foto op Hout": "Op jullie site staat antwoord binnen 24 uur. Daarnaast staat er een chat en een WhatsApp-knop, en wie daarop klikt rekent op minuten.",
"Fotofabriek": "Jullie desk is open van acht uur 's ochtends tot acht uur 's avonds. Op dezelfde pagina staat dat een mail binnen 24 uur wordt beantwoord.",
"Fred de la Bretoniere": "Op jullie klantenservicepagina loopt alles via de mail, een telefoonnummer staat er niet. Op Trustpilot gaan de klachten die er staan juist over die klantenservice.",
"Fresh n Rebel": "Jullie leveren in elf taal- en marktvarianten. Op de contactpagina staat alleen een mailadres, zonder telefoonnummer erbij.",
"Fromanteel": "Jullie hebben een winkel aan de Keizersgracht en een webshop in zestien taalvarianten. Op de contactpagina staat geen nummer om die winkel te bellen.",
"Greve Shoes": "Jullie klantenservice is bereikbaar tot vier uur 's middags. De belofte op dezelfde pagina is antwoord binnen 24 uur.",
"Grutto": "Elf losse websites zijn bij jullie samengevoegd tot een merk. Het contact loopt sindsdien via de mail, zonder telefoonnummer ernaast.",
"Horren Direct": "Jullie verkopen horren op maat, dus elke bestelling begint met opmeten. Op de site vond ik geen telefoonnummer om die maten mee te overleggen.",
"Jane Lushka": "Jullie site draait in 48 taal- en marktvarianten met 919 artikelen. Een eigen reviewpagina waar al die kopers iets kwijt kunnen, vond ik niet.",
"Just Franky": "Jullie sieraden zijn volledig personaliseerbaar en liggen daarnaast bij 36 juweliers. Op de contactpagina staat een mailadres en geen telefoonnummer.",
"Komono": "In jullie feed staan 1.309 artikelen, verdeeld over zes taal- en marktvarianten. Op de contactpagina staat support@komono.com als enige ingang.",
"Kraamcadeau": "Jullie klantenservice is bereikbaar van half negen tot half een. De rest van de dag staat de chat er nog wel.",
"LaDress": "Jullie webshop voert 491 artikelen in zes taalvarianten. Op Trustpilot valt het oordeel over de klantenservice in twee helften uiteen, met onbeantwoorde mails aan de ene kant.",
"Lekker Bikes": "Jullie beloven op de servicepagina antwoord binnen 24 uur. Die belofte geldt voor klanten in dertien markten, van Amsterdam tot Brisbane.",
"LingaDore": "Jullie klantenservice sluit op vrijdag om kwart voor drie. De belofte op dezelfde pagina is antwoord binnen een werkdag.",
"Loavies": "Jullie besteedden de logistiek uit omdat dat de beste manier bleek om de groeiambities te halen. Het klantcontact staat nog binnenshuis, met een belofte van 48 uur.",
"LouLou Essentiels": "Jullie hebben bijna elfduizend reviews verzameld. De balie waar die klanten terechtkomen, is open van negen tot vijf.",
"Malelions": "In jullie feed staan 2.568 artikelen, verdeeld over vier submerken. De belofte op de servicepagina is antwoord binnen twee werkdagen.",
"Marlies Dekkers": "Jullie site draait in 36 taal- en marktvarianten. De balie erachter is open van half tien tot vijf, van maandag tot en met vrijdag.",
"Matt Sleeps": "Jullie zetten in juli twee vacatures voor customer support online, en die staan er nog. De balie draait intussen in twee blokken, van tien tot vijf en van zes tot negen.",
"Metis Supplements": "Op jullie contactpagina staat hello@metissupplements.com en verder een chatvenster. Een telefoonnummer vond ik er niet.",
"Muchachomalo": "In jullie feed staan 1.725 artikelen en op Trustpilot ruim 1.600 reviews. De balie erachter is open van negen tot zes.",
"Namens Mij": "Jullie klantenservice is bereikbaar op maandag, dinsdag en donderdag tot half drie. De belofte op dezelfde pagina is antwoord binnen 24 uur.",
"Natural Heroes": "Jullie assortiment loopt van etherische olien tot tandenborstels van bamboe. Op de contactpagina staat een chat en een mailadres, zonder telefoonnummer ernaast.",
"PLNTS": "Jullie hebben ruim 22.000 reviews en verzenden levende planten. Op de contactpagina staat alleen een mailadres, zonder telefoonnummer.",
"PersonalSurprise": "Op jullie klantenservicepagina staat een reactietijd van 24 uur. Jullie verkopen cadeaus in vijf markten waar de naam van de ontvanger op staat, dus een fout is meteen zichtbaar.",
"Pieter Pot": "Op jullie site staat antwoord binnen twaalf uur. Achter die belofte zitten 528 producten en een systeem van potten dat heen en weer reist.",
"Podobrace": "Jullie omzet ging in korte tijd maal tien en er kwam een overname bij. De belofte op de servicepagina staat nog steeds op 24 uur.",
"Poederbaas": "Jullie webshop draait in 54 taal- en marktvarianten. In de reviews komt steeds dezelfde kritiek terug, over de snelheid van reageren.",
"Power Supplements": "Jullie klantenservice is bereikbaar van tien tot vijf. De webshop levert in vier markten en staat de andere negentien uur ook open.",
"Printenbind": "Jullie balie is open tot half tien 's avonds, en dat is langer dan bij vrijwel iedereen die ik bekeek. Er gaan duizenden orders per dag doorheen, veel ervan met een deadline van morgen.",
"Purewhite": "Jullie liggen bij ruim vijfhonderd retailers in zes landen. In de reviews schrijven klanten dat de klantenservice moeilijk te bereiken is.",
"Quotrell": "Jullie hebben duizenden reviews en vrijwel allemaal vijf sterren, met lof voor de klantenservice. Diezelfde service draait nu in elf taal- en marktvarianten.",
"Red-Rag": "Op jullie contactpagina staan twee mailadressen, info@red-rag.nl en service@red-rag.com. Een telefoonnummer staat er niet bij.",
"Rehab Footwear": "Jullie kwamen na het faillissement van Unlimited Footwear Group zelfstandig verder met het merk. De webshop voert inmiddels 373 artikelen.",
"Rosefield": "Jullie hebben ruim tweeduizend reviews op Trustpilot en nog eens tweeduizend op Judge.me. Op de contactpagina staat geen nummer om die klanten te woord te staan.",
"Sapph": "Radar schreef over klanten die maandenlang op hun geld wachtten. Sinds dit voorjaar zit er een nieuwe eigenaar en sinds mei een nieuwe CEO.",
"Seepje": "Jullie haalden 4,2 miljoen op en zoeken een CEO voor de volgende groeifase. De klantenservice belooft intussen antwoord binnen 24 uur.",
"Slaapkamerweb": "Jullie servicepagina zegt antwoord binnen 24 uur. Op dezelfde pagina staat een chatvenster dat meteen opengaat.",
"Somnox": "Jullie klantenservice is telefonisch bereikbaar van tien tot twaalf. Jullie verkopen een slaaprobot, en slecht slapen gebeurt 's nachts.",
"Sticky Lemon": "In jullie reviews noemen klanten de klantenservice de beste die ze kennen. Achter die service liggen inmiddels 465 artikelen in de feed.",
"Studio Ins en Outs": "Twee nieuwe eigenaressen namen deze zomer het roer over. De webshop die ze erbij kregen, voert 960 artikelen in vijf taalvarianten.",
"Summum Woman": "Sinds juli neemt Modexpress jullie B2C-orders en retouren over. Het klantcontact daarover komt nog op jullie eigen balie binnen, van tien tot zes.",
"Veneta": "Jullie leveren raamdecoratie op maat, dus elke bestelling begint met opmeten. Op de klantenservicepagina vond ik geen telefoonnummer om die maten te overleggen.",
"Violet Hamden": "Jullie klantenservice is bereikbaar van negen tot twaalf uur 's ochtends. De belofte op dezelfde pagina is antwoord binnen vijf werkdagen.",
"Wakuli": "Jullie koffie gaat op abonnement de deur uit, in vijf markten. Op de contactpagina staat een chat en een mailadres, zonder telefoonnummer.",
"Werk aan de Muur": "Op jullie contactpagina staat dat de telefoon en de mail van negen tot drie open zijn, en de chat 24 uur per dag. Achter die chat staan meer dan 26.000 makers met hun eigen werk.",
"Wolky": "Jullie maken al ruim veertig jaar comfortschoenen en leveren in vijf markten. In de reviews komt steeds terug dat het retourbeleid onduidelijk is.",
"Wolplein": "Jullie hebben 55 medewerkers en een webshop in 25 taalvarianten. In de reviews staat dat de klantenservice alleen 's ochtends te bereiken is.",
"Xtorm": "Jullie verkopen ongeveer een miljoen producten per jaar in meer dan zestig landen. De belofte op de servicepagina is antwoord binnen 48 uur.",
"Yogisha": "Op jullie servicepagina staat antwoord binnen twee werkdagen. Daaronder staat een telefoonnummer, voor wie dat te lang vindt duren.",
"Zenggi": "Jullie voeren twee merken naast elkaar, met 487 artikelen in de feed. Beide komen binnen op customerservice@zenggi.com, want een telefoonnummer staat er niet.",
}
